### ISSUE TITLE
li[role="separator"] shouldn't be recommended since it's invalid

### ISSUE THREAD

**Issue by cvrebert** [Heydon/REVENGE.CSS#12]
One of your error messages is:

> Do not use list items to divide up lists unless they have role = separator

However `<li role="separator">` is invalid per http://www.w3.org/TR/html5/dom.html#sec-implicit-aria-semantics :
- Language feature: `li` element whose parent is an `ol` or `ul` element
- Restrictions: If specified, `role` **must** be one of the following: `listitem`, `menuitem`, `menuitemcheckbox`, `menuitemradio`, `option`, `radio`, `tab`, `treeitem` or `presentation`

Note how `separator` is absent from that list.

Perhaps `presentation` should be recommended instead?

**Comment by rpokrovskij** [comment]
it is interesting that li[role="separator"] is allowed right now in (HTML 5.2):
https://www.w3.org/TR/html52/grouping-content.html#the-li-element

> listitem role (default - do not set), option, presentation, radio, **separator**, tab or treeitem.
