### ISSUE TITLE
`i` should be allowed as empty element?

### ISSUE THREAD

**Issue by XhmikosR** [Heydon/REVENGE.CSS#13]
Like when using Font Awesome

``` html
<i class="fa fa-facebook fa-2x"></i>
```

**Comment by deiga** [comment]
@XhmikosR `The HTML <i> element represents a range of text that is set off from the normal text for some reason.` Using Icon Fonts with `<i>` is semantically wrong.

**Comment by XhmikosR** [comment]
You do know you replied in a 4 year-old issue?

**Comment by deiga** [comment]
@XhmikosR An open issue, is an open issue is open until it's closed. Even older issues can be relevant.

**Comment by XhmikosR** [comment]
Nah, this was quite irrelevant since the day I made it. But well, our knowledge evolves by the time. :)
