### ISSUE TITLE
Not an issue just seeking opinion on updates to CSS

### ISSUE THREAD

**Issue by LaurenceRLewis** [Heydon/REVENGE.CSS#19]
Hi @Heydon 

I made a few changes in a forked version and if you get a spare moment would appreciate your comments.

https://github.com/Decrepidos/REVENGE.CSS

Added or removed the following:

Added not:span.fa and i.fa to exclude Font Awesomeicons hooks on empty elements.

Added i.fa:not([aria-hidden="true"])::after, span.fa:not([aria-hidden="true"])::after {
    content: 'Use aria-hidden="true on icons.' !important;
} to make sure aria-hidden is included on icons

Removed as <footer> requires role=contentInfo and <header> requires role=banner as these are already conveyed natively. W3C validator generates a warning if used.

/*
body > div#footer:not([role="contentinfo"])::after, body > div.footer:not([role="contentinfo"])::after {
	content: 'Use role="contentinfo" on this footer element or use native HTML5 <footer>.' !important;
}
body > div#header:not([role="banner"])::after, body > div.header:not([role="banner"])::after, body > div.banner:not([role="banner"])::after, body > div#banner:not([role="banner"])::after {
	content: 'Use role="banner" on this header element or use native <header>.' !important;
}
*/

/***
Added if div has class or ID of header but is not a native element include role. Considering if .banner #banner should be included
*/
div#header:not([role="banner"])::after, div.header:not([role="banner"])::after {
	content: 'Use role="banner" on this header element or use native <header>.' !important;
}
Regards
Laurence

**Comment by Heydon** [comment]
@Decrepidos I would accept a pull request for these, thanks!

**Comment by Decrepidos** [comment]
Great I will set it up. Thanks 😁

**Comment by Decrepidos** [comment]
Hopefully I did the Pull Request correctly. If not Yell and I'll try again :-)
