### ISSUE TITLE
Recommendation: sr-only class in Twitter Bootstrap

### ISSUE THREAD

**Issue by Decrepidos** [Heydon/REVENGE.CSS#20]
I find the sr-only class used for off-screen screen reader only text used in sites. Often it is used unnecessarily. For example: `<h2 class=”sr-only”> This is the site header</h2>`.
I recommend including the following to flag this.
.sr-only:after{
   content: 'Off-screen text for screen reader users. Is this text necessary?' !important; 
}

**Comment by Heydon** [comment]
@Decrepidos How would one see the warning message?

**Comment by Decrepidos** [comment]
Off course l’ll work on that one 😁
