### ISSUE TITLE
Wrong `img` rule

### ISSUE THREAD

**Issue by HugoGiraudel** [Heydon/REVENGE.CSS#6]
I believe there is a rule matching all correctly formated images:

``` css
img[alt]:not([alt=""])
```

This targets all `img` tags with an `alt` attribute which is not empty. So... Every properly formated image as far as I know. I believe you want to target:

``` css
img[alt=""]
```

... but you might want to override this rule for images in `figure`, because it's common practice to empty the `alt` attribute when there is a `figcaption`.

**Comment by deiga** [comment]
Please close issue :)
